// frontend-vue/src/components/NavBar.vue
<template>
  <nav class="navbar">
    <div class="navbar-container">
      <router-link to="/" class="navbar-brand">
        <i class="pi pi-bookmark"></i>
        <span>Interview Prep</span>
      </router-link>
      
      <div class="navbar-menu">
        <router-link to="/" class="navbar-link" exact>
          <i class="pi pi-home"></i>
          <span>Главная</span>
        </router-link>

        <router-link v-if="isAuthenticated" to="/trainer" class="navbar-link">
          <i class="pi pi-bolt"></i>
          <span>Тренажёр</span>
        </router-link>

        <router-link to="/interview-questions" class="navbar-link">
          <i class="pi pi-list"></i>
          <span>Вопросы</span>
        </router-link>

        <router-link v-if="isAuthenticated" to="/recordings" class="navbar-link">
          <i class="pi pi-video"></i>
          <span>Записи</span>
        </router-link>

        <router-link v-if="isAuthenticated" to="/test-assignments" class="navbar-link">
          <i class="pi pi-file-edit"></i>
          <span>Задания</span>
        </router-link>

        <router-link to="/hh-requirements" class="navbar-link">
          <i class="pi pi-chart-bar"></i>
          <span>Навыки</span>
        </router-link>
        
        <router-link v-if="isAdmin" to="/admin" class="navbar-link admin-link">
          <i class="pi pi-cog"></i>
          <span>Админка</span>
        </router-link>
      </div>
      
      <div class="navbar-right">
        <Chip :label="`${questionsCount} вопросов`" icon="pi pi-question-circle" />
        
        <template v-if="isAuthenticated">
          <div class="user-menu">
            <router-link :to="isAdmin ? '/admin' : '/profile'" class="user-chip-link" :title="isAdmin ? 'Админ-панель' : 'Профиль'">
              <Chip :label="displayName" :icon="isAdmin ? 'pi pi-shield' : 'pi pi-user'" class="user-chip" />
            </router-link>
            <button class="logout-btn" @click="handleLogout" title="Выйти">
              <i class="pi pi-sign-out"></i>
            </button>
          </div>
        </template>
        <template v-else>
          <router-link to="/login" class="login-btn">
            <i class="pi pi-sign-in"></i>
            <span>Войти</span>
          </router-link>
        </template>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useQuestionsStore } from '../store'
import { useAuthStore } from '../store/auth'

const router = useRouter()
const questionsStore = useQuestionsStore()
const authStore = useAuthStore()

const questionsCount = computed(() => questionsStore.questions.length)
const isAuthenticated = computed(() => authStore.isAuthenticated)
const isAdmin = computed(() => authStore.isAdmin)
const displayName = computed(() => authStore.displayName)

function handleLogout() {
  authStore.logout()
  router.push('/')
}
</script>

<style scoped>
.navbar {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%);
  background-size: 200% 200%;
  padding: 1.2rem 2rem;
  box-shadow: 0 8px 32px rgba(102, 126, 234, 0.4);
  position: sticky;
  top: 0;
  z-index: 1000;
  backdrop-filter: blur(10px);
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  animation: gradient-shift 15s ease infinite;
}

.navbar-container {
  max-width: 1400px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.navbar-brand {
  display: flex;
  align-items: center;
  gap: 0.9rem;
  text-decoration: none;
  color: white;
  font-size: 1.6rem;
  font-weight: 800;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
}

.navbar-brand i {
  transition: transform 0.4s ease;
  filter: drop-shadow(0 2px 4px rgba(0, 0, 0, 0.2));
}

.navbar-brand:hover {
  transform: scale(1.05);
  text-shadow: 0 4px 20px rgba(255, 255, 255, 0.3);
}

.navbar-brand:hover i {
  transform: rotate(10deg) scale(1.1);
}

.navbar-menu {
  display: flex;
  gap: 1rem;
  flex: 1;
  margin-left: 3rem;
}

.navbar-link {
  display: flex;
  align-items: center;
  gap: 0.6rem;
  text-decoration: none;
  color: rgba(255, 255, 255, 0.85);
  font-weight: 600;
  padding: 0.6rem 1.2rem;
  border-radius: 8px;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  position: relative;
  overflow: hidden;
}

.navbar-link::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(255, 255, 255, 0.1);
  transform: scaleX(0);
  transform-origin: left;
  transition: transform 0.3s ease;
  border-radius: 8px;
}

.navbar-link:hover::before,
.navbar-link.router-link-active::before {
  transform: scaleX(1);
}

.navbar-link:hover,
.navbar-link.router-link-active {
  color: white;
  background: rgba(255, 255, 255, 0.15);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
}

.navbar-link i {
  transition: transform 0.3s ease;
}

.navbar-link:hover i {
  transform: scale(1.2);
}

.navbar-right {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.user-menu {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.user-chip-link {
  text-decoration: none;
  transition: all 0.3s;
  border-radius: 16px;
}

.user-chip-link:hover .user-chip {
  background: rgba(255, 255, 255, 0.25) !important;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
}

.user-chip {
  background: rgba(255, 255, 255, 0.15) !important;
  color: white !important;
  border: 1px solid rgba(255, 255, 255, 0.2) !important;
  cursor: pointer;
}

.logout-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border-radius: 8px;
  border: 1px solid rgba(255, 255, 255, 0.2);
  background: rgba(255, 255, 255, 0.1);
  color: rgba(255, 255, 255, 0.8);
  cursor: pointer;
  transition: all 0.3s;
}

.logout-btn:hover {
  background: rgba(239, 68, 68, 0.3);
  border-color: rgba(239, 68, 68, 0.5);
  color: white;
}

.login-btn {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  text-decoration: none;
  color: white;
  padding: 0.5rem 1.2rem;
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.15);
  border: 1px solid rgba(255, 255, 255, 0.2);
  font-weight: 600;
  font-size: 0.9rem;
  transition: all 0.3s;
}

.login-btn:hover {
  background: rgba(255, 255, 255, 0.25);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
}
</style>

// frontend-shadcn/src/components/layout/navbar.tsx
import { useEffect, useState } from 'react'
import { Link, NavLink, useNavigate } from 'react-router-dom'
import { Menu, X, LogIn, LogOut, User as UserIcon, Shield } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { ThemeToggle } from './theme-toggle'
import { BrandLogo } from './brand-logo'
import { cn } from '@/lib/utils'
import { useAuthStore } from '@/store/auth'

const navItems: Array<{ to: string; label: string; auth?: boolean; admin?: boolean }> = [
  { to: '/', label: 'Главная' },
  { to: '/interview-questions', label: 'Вопросы' },
  { to: '/trainer', label: 'Тренажёр', auth: true },
  { to: '/ai-interview', label: 'AI Interview', auth: true },
  { to: '/mock-interview', label: 'Mock', auth: true },
  { to: '/recordings', label: 'Записи', auth: true },
  { to: '/test-assignments', label: 'Задания', auth: true },
  { to: '/hh-requirements', label: 'HH-навыки' },
  { to: '/suggest', label: 'Предложить' },
  { to: '/admin', label: 'Админ', auth: true, admin: true },
]

export function NavBar() {
  const [open, setOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const navigate = useNavigate()
  const { user, isAuthenticated, logout } = useAuthStore()

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 8)
    onScroll()
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  const visibleItems = navItems.filter((it) => {
    if (it.admin) return user?.role === 'admin'
    if (it.auth) return isAuthenticated
    return true
  })

  return (
    <header
      className={cn(
        'sticky top-0 z-40 w-full transition-colors',
        scrolled ? 'border-b border-border/60 glass' : 'bg-transparent'
      )}
    >
      <div className="mx-auto flex h-14 max-w-7xl items-center justify-between gap-3 px-4 sm:px-6">
        <div className="flex items-center gap-6">
          <BrandLogo />
          <nav className="hidden items-center gap-1 md:flex">
            {visibleItems.map((item) => (
              <NavLink
                key={item.to}
                to={item.to}
                end={item.to === '/'}
                className={({ isActive }) =>
                  cn(
                    'rounded-md px-3 py-1.5 text-sm font-medium transition-colors',
                    isActive
                      ? 'bg-accent text-accent-foreground'
                      : 'text-muted-foreground hover:bg-accent/50 hover:text-foreground'
                  )
                }
              >
                {item.label}
              </NavLink>
            ))}
          </nav>
        </div>

        <div className="flex items-center gap-2">
          <ThemeToggle />
          {isAuthenticated && user ? (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" aria-label="Профиль" className="rounded-full">
                  <Avatar className="h-8 w-8">
                    <AvatarFallback className="bg-gradient-to-br from-violet-500 to-cyan-500 text-white text-xs font-bold uppercase">
                      {user.username?.slice(0, 2)}
                    </AvatarFallback>
                  </Avatar>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-56">
                <DropdownMenuLabel>
                  <div className="flex flex-col">
                    <span className="font-medium">{user.username}</span>
                    {user.email && <span className="text-xs text-muted-foreground">{user.email}</span>}
                  </div>
                </DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem onClick={() => navigate('/profile')} className="gap-2">
                  <UserIcon className="h-4 w-4" /> Профиль
                </DropdownMenuItem>
                {user.role === 'admin' && (
                  <DropdownMenuItem onClick={() => navigate('/admin')} className="gap-2">
                    <Shield className="h-4 w-4" /> Админ-панель
                  </DropdownMenuItem>
                )}
                <DropdownMenuSeparator />
                <DropdownMenuItem
                  onClick={() => {
                    logout()
                    navigate('/')
                  }}
                  className="gap-2 text-destructive focus:text-destructive"
                >
                  <LogOut className="h-4 w-4" /> Выйти
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          ) : (
            <Button asChild size="sm" variant="outline" className="hidden sm:inline-flex">
              <Link to="/login">
                <LogIn className="h-4 w-4" /> Войти
              </Link>
            </Button>
          )}
          <Button
            size="icon"
            variant="ghost"
            className="md:hidden"
            onClick={() => setOpen((o) => !o)}
            aria-label="Меню"
          >
            {open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
          </Button>
        </div>
      </div>

      {open && (
        <div className="border-t border-border/60 glass md:hidden">
          <nav className="mx-auto flex max-w-7xl flex-col gap-1 px-4 py-3">
            {visibleItems.map((item) => (
              <NavLink
                key={item.to}
                to={item.to}
                end={item.to === '/'}
                onClick={() => setOpen(false)}
                className={({ isActive }) =>
                  cn(
                    'rounded-md px-3 py-2 text-sm font-medium',
                    isActive
                      ? 'bg-accent text-accent-foreground'
                      : 'text-muted-foreground hover:bg-accent/50'
                  )
                }
              >
                {item.label}
              </NavLink>
            ))}
            {!isAuthenticated && (
              <Button asChild size="sm" variant="outline" className="mt-2 w-full">
                <Link to="/login" onClick={() => setOpen(false)}>
                  <LogIn className="h-4 w-4" /> Войти
                </Link>
              </Button>
            )}
          </nav>
        </div>
      )}
    </header>
  )
}
